global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ingestion_service'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'simulator'
    static_configs:
      - targets: ['host.docker.internal:8001']

  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
